/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as auctionSol from "./Auction.sol";
export type { auctionSol };
export type { PatikaBears } from "./PatikaBears";
